version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/configuration.yaml:/config/configuration.yaml
      - ./thingsboard:/config/custom_components/thingsboard
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  ha_config: