services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2025.1.4"
    volumes:
      - ha_config:/config
      - ./custom_components/thingsboard:/config/custom_components/thingsboard
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  ha_config: